# fly.toml app configuration file generated for wher-backend on 2023-10-30T20:51:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wher-backend"
primary_region = "hkg"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ENVIRONTMENT="production"
  PORT=8080
  DB_PORT=3306
  DB_NAME="wher_prod"
  DB_USERNAME="prod"
  LOG_LEVEL="debug"

[deploy]
  release_command = "npm run migration:up"
  wait_timeout = "10m"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  http_checks = []
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"